@baseUrl = http://localhost:4004

### REST - Get All Categories (entity)
GET {{baseUrl}}/rest/rest/Categories

###

### REST - getCategories action
POST {{baseUrl}}/rest/rest/getCategories
Content-Type: application/json

{}

###

### OData - Get All Categories (entity)
GET {{baseUrl}}/odata/v4/odata/Categories

###

### OData - getCategories action
POST {{baseUrl}}/odata/v4/odata/getCategories
Content-Type: application/json

{}

###

### REST - Upload CSV file
POST {{baseUrl}}/api/document/upload/uploadFile
Content-Type: multipart/form-data; boundary=----FormBoundary7MA4YWxkTrZu0gW

------FormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="testcsv.csv"
Content-Type: text/csv

< ./testcsv.csv
------FormBoundary7MA4YWxkTrZu0gW--

###

### REST - Get all uploaded files
GET {{baseUrl}}/rest/rest/FileUploads
